{"uid":"d8a2c7c5a3994767","name":"test_reg[log_fail_wrong_pwd]","fullName":"tests.test_login#test_reg","historyId":"6e2839286a9f9fd468612a1a7cc27fc6","time":{"start":1753170572469,"stop":1753170572543,"duration":74},"status":"broken","statusMessage":"selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=138.0.7204.100)\nStacktrace:\n#0 0x5568aa4817da <unknown>\n#1 0x5568a9f262e0 <unknown>\n#2 0x5568a9f1d4c1 <unknown>\n#3 0x5568a9f0e789 <unknown>\n#4 0x5568a9f104d0 <unknown>\n#5 0x5568a9f0eb2e <unknown>\n#6 0x5568a9f0e49a <unknown>\n#7 0x5568a9f0e175 <unknown>\n#8 0x5568a9f0bfd5 <unknown>\n#9 0x5568a9f0c7ba <unknown>\n#10 0x5568a9f29809 <unknown>\n#11 0x5568a9fc4335 <unknown>\n#12 0x5568a9f9d8b2 <unknown>\n#13 0x5568a9fc371c <unknown>\n#14 0x5568a9f9d683 <unknown>\n#15 0x5568a9f69b5b <unknown>\n#16 0x5568a9f6af31 <unknown>\n#17 0x5568aa44672b <unknown>\n#18 0x5568aa44a534 <unknown>\n#19 0x5568aa42d229 <unknown>\n#20 0x5568aa44b0d8 <unknown>\n#21 0x5568aa41161f <unknown>\n#22 0x5568aa46edd8 <unknown>\n#23 0x5568aa46efb6 <unknown>\n#24 0x5568aa480af6 <unknown>\n#25 0x7fc3b549caa4 <unknown>\n#26 0x7fc3b5529c3c <unknown>","statusTrace":"driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2074764a48cd15d70a00dc7eea223471\")>\nuser = 'ok858585ok@gmail.com', pwd = '35438438438', expected = '帳號或密碼錯誤'\nrequest = <FixtureRequest for <Function test_reg[log_fail_wrong_pwd]>>\n\n    @pytest.mark.parametrize(\"user, pwd, expected\", params)\n    \n    def test_reg(driver, user, pwd, expected,request):\n        page=IndexPage(driver)\n>       page.open()\n\ntests/test_login.py:14: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nscr/Index_page.py:12: in open\n    self.driver.get(self.url)\n/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:479: in get\n    self.execute(Command.GET, {\"url\": url})\n/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py:454: in execute\n    self.error_handler.check_response(response)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.remote.errorhandler.ErrorHandler object at 0x7f484a26b4a0>\nresponse = {'status': 500, 'value': '{\"value\":{\"error\":\"unknown error\",\"message\":\"unknown error: net::ERR_CONNECTION_REFUSED\\\\n  ...\\\\n#24 0x5568aa480af6 \\\\u003Cunknown>\\\\n#25 0x7fc3b549caa4 \\\\u003Cunknown>\\\\n#26 0x7fc3b5529c3c \\\\u003Cunknown>\\\\n\"}}'}\n\n    def check_response(self, response: dict[str, Any]) -> None:\n        \"\"\"Checks that a JSON response from the WebDriver does not have an\n        error.\n    \n        :Args:\n         - response - The JSON response from the WebDriver server as a dictionary\n           object.\n    \n        :Raises: If the response contains an error message.\n        \"\"\"\n        status = response.get(\"status\", None)\n        if not status or status == ErrorCode.SUCCESS:\n            return\n        value = None\n        message = response.get(\"message\", \"\")\n        screen: str = response.get(\"screen\", \"\")\n        stacktrace = None\n        if isinstance(status, int):\n            value_json = response.get(\"value\", None)\n            if value_json and isinstance(value_json, str):\n                try:\n                    value = json.loads(value_json)\n                    if isinstance(value, dict):\n                        if len(value) == 1:\n                            value = value[\"value\"]\n                        status = value.get(\"error\", None)\n                        if not status:\n                            status = value.get(\"status\", ErrorCode.UNKNOWN_ERROR)\n                            message = value.get(\"value\") or value.get(\"message\")\n                            if not isinstance(message, str):\n                                value = message\n                                message = message.get(\"message\")\n                        else:\n                            message = value.get(\"message\", None)\n                except ValueError:\n                    pass\n    \n        exception_class: type[WebDriverException]\n        e = ErrorCode()\n        error_codes = [item for item in dir(e) if not item.startswith(\"__\")]\n        for error_code in error_codes:\n            error_info = getattr(ErrorCode, error_code)\n            if isinstance(error_info, list) and status in error_info:\n                exception_class = getattr(ExceptionMapping, error_code, WebDriverException)\n                break\n        else:\n            exception_class = WebDriverException\n    \n        if not value:\n            value = response[\"value\"]\n        if isinstance(value, str):\n            raise exception_class(value)\n        if message == \"\" and \"message\" in value:\n            message = value[\"message\"]\n    \n        screen = None  # type: ignore[assignment]\n        if \"screen\" in value:\n            screen = value[\"screen\"]\n    \n        stacktrace = None\n        st_value = value.get(\"stackTrace\") or value.get(\"stacktrace\")\n        if st_value:\n            if isinstance(st_value, str):\n                stacktrace = st_value.split(\"\\n\")\n            else:\n                stacktrace = []\n                try:\n                    for frame in st_value:\n                        line = frame.get(\"lineNumber\", \"\")\n                        file = frame.get(\"fileName\", \"<anonymous>\")\n                        if line:\n                            file = f\"{file}:{line}\"\n                        meth = frame.get(\"methodName\", \"<anonymous>\")\n                        if \"className\" in frame:\n                            meth = f\"{frame['className']}.{meth}\"\n                        msg = \"    at %s (%s)\"\n                        msg = msg % (meth, file)\n                        stacktrace.append(msg)\n                except TypeError:\n                    pass\n        if exception_class == UnexpectedAlertPresentException:\n            alert_text = None\n            if \"data\" in value:\n                alert_text = value[\"data\"].get(\"text\")\n            elif \"alert\" in value:\n                alert_text = value[\"alert\"].get(\"text\")\n            raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n>       raise exception_class(message, screen, stacktrace)\nE       selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\nE         (Session info: chrome=138.0.7204.100)\nE       Stacktrace:\nE       #0 0x5568aa4817da <unknown>\nE       #1 0x5568a9f262e0 <unknown>\nE       #2 0x5568a9f1d4c1 <unknown>\nE       #3 0x5568a9f0e789 <unknown>\nE       #4 0x5568a9f104d0 <unknown>\nE       #5 0x5568a9f0eb2e <unknown>\nE       #6 0x5568a9f0e49a <unknown>\nE       #7 0x5568a9f0e175 <unknown>\nE       #8 0x5568a9f0bfd5 <unknown>\nE       #9 0x5568a9f0c7ba <unknown>\nE       #10 0x5568a9f29809 <unknown>\nE       #11 0x5568a9fc4335 <unknown>\nE       #12 0x5568a9f9d8b2 <unknown>\nE       #13 0x5568a9fc371c <unknown>\nE       #14 0x5568a9f9d683 <unknown>\nE       #15 0x5568a9f69b5b <unknown>\nE       #16 0x5568a9f6af31 <unknown>\nE       #17 0x5568aa44672b <unknown>\nE       #18 0x5568aa44a534 <unknown>\nE       #19 0x5568aa42d229 <unknown>\nE       #20 0x5568aa44b0d8 <unknown>\nE       #21 0x5568aa41161f <unknown>\nE       #22 0x5568aa46edd8 <unknown>\nE       #23 0x5568aa46efb6 <unknown>\nE       #24 0x5568aa480af6 <unknown>\nE       #25 0x7fc3b549caa4 <unknown>\nE       #26 0x7fc3b5529c3c <unknown>\n\n/opt/hostedtoolcache/Python/3.12.11/x64/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py:232: WebDriverException","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"driver","time":{"start":1753170571954,"stop":1753170572350,"duration":396},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1753170572673,"stop":1753170572731,"duration":58},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_login"},{"name":"host","value":"fv-az1694-65"},{"name":"thread","value":"4478-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected","value":"'帳號或密碼錯誤'"},{"name":"pwd","value":"'35438438438'"},{"name":"user","value":"'ok858585ok@gmail.com'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d8a2c7c5a3994767.json","parameterValues":["'帳號或密碼錯誤'","'35438438438'","'ok858585ok@gmail.com'"]}